version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: skillsmatrix
          MYSQL_USER: skillsmatrixuser
          MYSQL_PASSWORD: 123456
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/laravel

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev mysql-client
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -u root -e "create database skillsmatrix;"
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) 
